<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CategoryNewForm extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $formRules = [
            'name'=>[
                'required',
                Rule::unique('category_news','name')->ignore($this->id),
            ],
        ];
        return $formRules;
    }
    public function messages()
    {
        $message = [
            'name.required'=>"Tên chuyên mục không để trống!",
            'name.unique'=>"Tên chuyên mục đã tồn tại!",
        ];
        return $message; // TODO: Change the autogenerated stub
    }
}
