<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class NewFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $formRules = [
            "title"=>[
                "required",
                "min:8",
                Rule::unique('news')->ignore($this->id),
            ],
            "image"=>[
                'required',
            ],
            "image2"=>[
                'required',
            ],
            "content"=>[
                'required','min:20'
            ],
            "cate_id"=>[
                'required',"integer"
            ]
        ];
        return $formRules;
    }
    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        $message=[
            "title.required"=>"Bạn chưa nhập tiêu đề bản tin",
            "title.unique"=>"Tên tiêu đề tồn tại",
            "title.min"=>"Tiêu đề tối thiểu 8 ký tự",
            "image.required"=>"Bạn chưa chọn ảnh",
            "image2.required"=>"Bạn chưa chọn ảnh",
            "content.required"=>"Nội dung không để trống",
            "content.min"=>"Nội dung chứa ít nhất 20 ký tự",
            "cate_id.required"=>"Bạn chưa chọn chuyên mục",
            "cate_id.integer"=>"Bạn chưa chọn tên chuyên mục",
        ];
        return $message;
    }
}
