<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ProductRequestForm extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
       $formRules = [
           "name"=>[
               'required',
                Rule::unique('products')->ignore($this->id),
               'min:3'
           ],
           "shorts"=>[
                'required',
                'min:20'
           ],
           "price"=>[
               "required",
               "numeric",
           ],
           "price_sale"=>[
               "numeric",
                "lt:price"
           ],
           "brand"=>[
               "required",
           ],
           "image"=>[
               "required"
           ],
           "thumbnail1"=>[
               "required"
           ],
           "thumbnail2"=>[
               "required"
           ],
           "thumbnail3"=>[
               "required"
           ],
           "sku"=>[
               "required"
           ],
           "cate_id"=>[
               "required"
           ],
           "description"=>[
               "min:20"
           ],
       ];
       return $formRules;
    }
    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        $message = [
            "name.required" => "Tên sản phẩm không bỏ trống.",
            "name.unique"=>"Tên sản phẩm tồn tại.",
            "name.min"=>"Tên sản phẩm tối thiểu 3 ký tự.",
            "shorts.required"=>"Mô tả ngắn không để trống.",
            "shorts.min"=>"Mô tả tối thiểu 20 ký tự.",
            "price.required"=>"Giá không để trống.",
            "price.numeric"=>"Giá phải là số.",
            "price_sale.numeric"=>"Giá sale phải là số.",
            "price_sale.lt"=>"Giá sale phải nhỏ hơn giá gốc.",
            "brand.required"=>"Chưa nhập thương hiệu.",
            "sku.required"=>"SKU chưa được nhập.",
            "cate_id.required"=>"Mã danh mục không để trống.",
            "image.required"=>"Hình ảnh không để trống.",
            "thumbnail1.required"=>"Hình ảnh không để trống.",
            "thumbnail2.required"=>"Hình ảnh không để trống.",
            "thumbnail3.required"=>"Hình ảnh không để trống.",
            "description.min"=>"Mô tả dài tối thiểu 20 ký tự",
        ];
        return $message;
    }
}
