<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UserForm extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rulesForm = [
            "name"=>[
                'required',
            ],
            "email"=>[
                'required',
                Rule::unique('users')->ignore($this->id),
                "regex:/(.+)@(.+)\.(.+)/i"
            ],
            "password"=>[
                'required',
                "min:8"
            ],


        ];
        return $rulesForm;
    }
    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        $message = [
            "name.required" => "Bạn chưa nhập họ tên.",
            "email.required"=> "Bạn chưa nhập Email.",
            "email.regex"=>"Đinh dạng Email chưa đúng.",
            'password.required'=>"Mật khẩu không để trống.",
            "password.min"=>"Mật khẩu tối thiểu 8 ký tự.",
        ];
        return $message;
    }
}
